# Generated by Django 4.1.1 on 2022-10-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='Vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crud',
            name='Vehicle_type',
            field=models.CharField(max_length=20),
        ),
    ]
